name: Generate Doxygen Documentation

on:
  push:
    tags:
      - '*'

jobs:
  generate_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: html
